feature: pre-commit script improved to check DI graph

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -1,7 +1,5 @@
 #!/bin/sh
-echo "*************************************************"
-echo "*               Running detekt...               *"
-echo "*************************************************"
+echo "Detekt: Running"
 
 JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
 export JAVA_HOME
@@ -12,14 +10,24 @@ EXIT_CODE=$?
 if [ ${EXIT_CODE} -ne 0 ]; then
     cat ${OUTPUT}
     rm ${OUTPUT}
-    echo "*************************************************"
-    echo "*            Static Analysis Failed             *"
-    echo "* Please fix the above issues before committing *"
-    echo "*************************************************"
+    echo "Detekt: Failed!"
     exit ${EXIT_CODE}
 else
     rm ${OUTPUT}
-    echo "*************************************************"
-    echo "*       Static analysis no problems found       *"
-    echo "*************************************************"
+    echo "Detekt: Success!"
+fi
+
+echo "Test DI graph: Running"
+
+OUTPUT="/tmp/tests-result"
+./gradlew :app:testDebugUnitTest -i --tests DependencyGraphTest > ${OUTPUT}
+EXIT_CODE=$?
+if [ ${EXIT_CODE} -ne 0 ]; then
+    cat ${OUTPUT} | grep -E " > |BUILD"
+    rm ${OUTPUT}
+    echo "Test DI graph: Failed!"
+    exit ${EXIT_CODE}
+else
+    rm ${OUTPUT}
+    echo "Test DI graph: Success!"
 fi
